name: Backend pull request workflow
"on": pull_request

jobs:
  backend-tests:
    name: Backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install packages
        run: cd backend && npm ci

      - name: Install functions packages
        run: cd backend/functions && npm ci

      - name: Unit tests
        run: cd backend && npm run test:unit

      - name: Integration tests
        run: cd backend && npm run test:integration
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: End to end tests
        run: cd backend && npm run test:e2e
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
