name: Deploy backend to staging on pull request
on: workflow_dispatch

jobs:
  release-and-deploy-production:
    name: Backend deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-backend-nodemodules-

      - name: Install packages
        run: cd backend && yarn install --frozen-lockfile --prefer-offline

      - name: Install functions packages
        run: cd backend/functions && npm install

      - name: Release & Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: cd backend && npx semantic-release -d

      - name: Deploy
        run: |
          cd backend
          yarn add firebase-tools
          yarn deploy:production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
