name: Backend pull request workflow
"on": pull_request

jobs:
  backend-tests:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-backend-nodemodules-

      - name: Install packages
        run: cd backend && yarn install --frozen-lockfile --prefer-offline

      - name: Install functions packages
        run: cd backend/functions && npm install

      - name: Unit tests
        run: cd backend && yarn test:unit

      - name: Integration tests
        run: cd backend && yarn test:integration
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: End to end tests
        run: cd backend && yarn test:e2e
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
