name: Frontend deploy to staging
on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend*"

jobs:
  release:
    name: Frontend deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-frontend-nodemodules-

      - name: Install packages
        run: cd frontend && yarn install --frozen-lockfile --prefer-offline

      - name: Test & build
        run: cd frontend && yarn run build && yarn run test

      - name: Deploy
        run: |
          cd frontend
          yarn add firebase-tools
          yarn firebase deploy --project staging --only hosting --token=${{ secrets.FIREBASE_TOKEN }}
